export const SIGN_UP = {
  SUCCESS: "SIGN_UP_SUCCESS",
  PENDING: "SIGN_UP_PENDING",
  ERROR: "SIGN_UP_ERROR",
};

export const SIGN_OUT = {
  SUCCESS: "SIGN_OUT_SUCCESS",
  PENDING: "SIGN_OUT_PENDING",
  ERROR: "SIGN_OUT_ERROR",
};

export const SIGN_IN = {
  SUCCESS: "SIGN_IN_SUCCESS",
  PENDING: "SIGN_IN_PENDING",
  ERROR: "SIGN_IN_ERROR",
};

export const AUTH = {
  SUCCESS: "AUTH_SUCCESS",
  PENDING: "AUTH_PENDING",
  ERROR: "AUTH_ERROR",
  NOT_AUTH: "AUTH_NOT_AUTH",
};

export const GET_POSTS = {
  SUCCESS: "GET_POSTS_SUCCESS",
  PENDING: "GET_POSTS_PENDING",
  ERROR: "GET_POSTS_ERROR",
};
