export const SIGN_UP = {
  SUCCESS: "SIGN_UP_SUCCESS",
  PENDING: "SIGN_UP_PENDING",
  ERROR: "SIGN_UP_ERROR",
};

export const SIGN_OUT = {
  SUCCESS: "SIGN_OUT_SUCCESS",
  PENDING: "SIGN_OUT_PENDING",
  ERROR: "SIGN_OUT_ERROR",
};

export const SIGN_IN = {
  SUCCESS: "SIGN_IN_SUCCESS",
  PENDING: "SIGN_IN_PENDING",
  ERROR: "SIGN_IN_ERROR",
};

export const AUTH = {
  SUCCESS: "AUTH_SUCCESS",
  PENDING: "AUTH_PENDING",
  ERROR: "AUTH_ERROR",
  NOT_AUTH: "AUTH_NOT_AUTH",
};

export const GET_POSTS = {
  SUCCESS: "GET_POSTS_SUCCESS",
  PENDING: "GET_POSTS_PENDING",
  ERROR: "GET_POSTS_ERROR",
};

export const CREATE_POSTS = {
  SUCCESS: "CREATE_POSTS_SUCCESS",
  PENDING: "CREATE_POSTS_PENDING",
  ERROR: "CREATE_POSTS_ERROR",
};
export const LIKE = {
  SUCCESS: "LIKE_SUCCESS",
  PENDING: "LIKE_PENDING",
  ERROR: "LIKE_ERROR",
};

export const DELETE_COMMENT = {
  SUCCESS: "DELETE_SUCCESS",
  PENDING: "DELETE_PENDING",
  ERROR: "DELETE_ERROR",
};
export const DESCRIPTION = {
  SUCCESS: "DESCRIPTION_SUCCESS",
  PENDING: "DESCRIPTION_PENDING",
  ERROR: "DESCRIPTION_ERROR",
};
export const USER_DATA = {
  SUCCESS: "USER_DATA_SUCCESS",
  PENDING: "USER_DATA_PENDING",
  ERROR: "USER_DATA_ERROR",
};